steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run/radiolism-api'
      - '.'

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run/radiolism-api'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'radiolism-api'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run/radiolism-api'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run/radiolism-api'

options:
  logging: CLOUD_LOGGING_ONLY